# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fb42c61fa2d32e5f78f9a90d420c235eb1d399d2c2dda617de4dd27c41ed50dbd467e5808cfaf22c440b187170735c1bd2da2a420a1dec7f8b6fb8a139b94a3

test:
  secret_key_base: 66fb0957f6cc651b80cbab5a17e3019e27bc673399279238d58ecb413422d7214885d8b50ba77940632a4d25bdc7682491934ecdd545e0bfb75a88e08965baa2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
